version: '3.7'

services:
  
  consul-server:
    image: hashicorp/consul:1.10.0
    container_name: consul-server
    restart: always
    volumes:
     - ./server.json:/consul/config/server.json:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  consul-client:
    image: hashicorp/consul:1.10.0
    container_name: consul-client
    restart: always
    volumes:
     - ./client.json:/consul/config/client.json:ro
    networks:
      - consul
    command: "agent"

  consul-registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    restart: always
    volumes:
     - var/run/docker.sock:/tmp/docker.sock
    command: -ip 192.168.1.1 consul://localhost:8500
    networks:
      - consul

networks:
  consul:
    driver: bridge