#this is for share dependencies
version: '3'
services:
  node-app:
    build:
      context: 
    
    environment:
      - PORT=3000
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    environment:
      - MONGO
    volumes:
      - mongo-db: